# region imports
from AlgorithmImports import *
import numpy as np
# endregion


class ORB_V10_Trial(QCAlgorithm):
    """
    ORB V10 Exploration Trial: Phase6_BestCombination
    Auto-generated by orchestrator.py
    """

    def initialize(self):
        self.set_start_date(2018, 1, 1)
        self.set_end_date(2025, 12, 31)
        self._initial_capital = 500000
        self.set_cash(self._initial_capital)

        # ── Core Parameters ─────────────────────────────────────
        self.reward_risk_ratio = 2.0
        self.min_range_pct = 0.0015
        self.max_range_pct = 0.015
        self.max_contracts = 20
        self.sma_period = 20
        self.confirmation_minutes = 7

        # ── Dual Vol Filter ─────────────────────────────────────
        self.use_dual_vol_filter = True
        self.vol_lookback = 20
        self.min_realized_vol = 0.12
        self.min_vix = 15.0

        # ── Novel Regime Filters ────────────────────────────────
        self.use_atr_compression = False
        self.atr_pctile_threshold = 20

        self.use_opening_gap = False
        self.max_gap_pct = 0.015

        self.use_vix_compression = True
        self.vix_drop_pct = 0.2
        self.vix_drop_days = 10
        self.vix_compression_ceil = 18.0

        self.use_adaptive_range = False
        self.adaptive_atr_period = 60

        self.use_overnight_vol = False
        self.overnight_vol_mult = 2.0

        # ── ML Regime Filter ────────────────────────────────────
        self.use_ml_filter = False
        self.ml_coefficients = None  # dict or None
        self.ml_intercept = 0.0

        # ── Equity Export ───────────────────────────────────────
        self.export_equity = True

        # ── Instrument Configuration ────────────────────────────
        self.instrument_configs = {
        "ES": {
            "contract": Futures.Indices.SP_500_E_MINI,
            "range_start_hour": 9, "range_start_min": 30,
            "range_end_hour": 9, "range_end_min": 45,
            "flatten_hour": 15, "flatten_min": 45,
            "risk_per_trade": 0.010,
        },
        "NQ": {
            "contract": Futures.Indices.NASDAQ_100_E_MINI,
            "range_start_hour": 9, "range_start_min": 30,
            "range_end_hour": 9, "range_end_min": 45,
            "flatten_hour": 15, "flatten_min": 45,
            "risk_per_trade": 0.005,
        },
    }

        # ── Initialize Futures ──────────────────────────────────
        self.futures = {}
        self.symbol_keys = {}
        self.current_contracts = {}
        self._previous_contracts = {}

        for key, cfg in self.instrument_configs.items():
            future = self.add_future(
                cfg["contract"],
                resolution=Resolution.MINUTE,
                data_normalization_mode=DataNormalizationMode.BACKWARDS_RATIO,
                data_mapping_mode=DataMappingMode.OPEN_INTEREST,
                contract_depth_offset=0,
            )
            self.futures[future.symbol] = future
            self.symbol_keys[future.symbol] = key

        # ── State ───────────────────────────────────────────────
        self.daily_state = {k: self._empty_state() for k in self.instrument_configs}
        self._trend_cache = {}
        self._trend_cache_date = None

        self._spy = self.add_equity("SPY", Resolution.DAILY).symbol
        self._spy_start_price = None

        self._vix = self.add_data(CBOE, "VIX", Resolution.DAILY).symbol
        self._current_vix = None
        self._prev_vix_10d = []

        self._vol_skip_today = False
        self._filter_skip_today = False

        # Equity export
        self._equity_log = []
        self._last_equity_date = None

        # Yearly tracking for runtime stats
        self._year_start_equity = {}
        self._daily_returns = {}
        self._prev_equity = None
        self._vol_skip_count = {}
        self._year_trades = {}

        # ATR compression state
        self._spy_atr_5 = None
        self._spy_atr_60_history = []

        # Overnight vol state
        self._prev_close = {}
        self._overnight_ranges = {}

        # ── Scheduled Events ────────────────────────────────────
        self.schedule.on(self.date_rules.every_day(), self.time_rules.at(0, 0), self._reset_daily_state)
        self.schedule.on(self.date_rules.every_day(), self.time_rules.at(9, 25), self._check_all_filters)
        self.schedule.on(self.date_rules.every_day(), self.time_rules.at(15, 45), self._flatten_all)
        self.schedule.on(self.date_rules.every_day(), self.time_rules.at(15, 50), self._record_daily)
        self.set_warm_up(timedelta(days=90))

    # ── Filter Logic ────────────────────────────────────────────

    def _check_all_filters(self):
        if self.is_warming_up:
            return

        self._vol_skip_today = False
        self._filter_skip_today = False

        # Dual vol filter
        if self.use_dual_vol_filter:
            vol_skip = False
            vix_skip = False
            try:
                h = self.history(self._spy, self.vol_lookback + 2, Resolution.DAILY)
                if not h.empty and len(h) >= self.vol_lookback:
                    closes = h["close"].values
                    rets = np.diff(closes) / closes[:-1]
                    realized_vol = float(np.std(rets[-self.vol_lookback:], ddof=1) * np.sqrt(252))
                    vol_skip = realized_vol < self.min_realized_vol

                    # ATR compression filter (uses same history)
                    if self.use_atr_compression:
                        daily_ranges = []
                        if len(h) >= 60:
                            highs = h["high"].values if "high" in h.columns else closes
                            lows = h["low"].values if "low" in h.columns else closes
                            daily_ranges = highs - lows
                            atr_5 = float(np.mean(daily_ranges[-5:]))
                            atr_60 = daily_ranges[-60:]
                            pctile_20 = float(np.percentile(atr_60, self.atr_pctile_threshold))
                            if atr_5 < pctile_20:
                                self._filter_skip_today = True
            except:
                pass

            if self._current_vix is not None:
                if self._current_vix < self.min_vix:
                    vix_skip = True

                # VIX compression proxy
                if self.use_vix_compression and len(self._prev_vix_10d) >= self.vix_drop_days:
                    vix_ago = self._prev_vix_10d[-self.vix_drop_days]
                    if vix_ago > 0:
                        vix_change = (self._current_vix - vix_ago) / vix_ago
                        if vix_change < -self.vix_drop_pct and self._current_vix < self.vix_compression_ceil:
                            self._filter_skip_today = True

            self._vol_skip_today = vol_skip or vix_skip

            year = self.time.year
            if self._vol_skip_today and year in self._vol_skip_count:
                self._vol_skip_count[year] += 1

        # Opening gap filter
        if self.use_opening_gap and not self._filter_skip_today:
            try:
                h = self.history(self._spy, 2, Resolution.DAILY)
                if not h.empty and len(h) >= 2:
                    prev_close = h["close"].values[-2]
                    today_open = h["open"].values[-1] if "open" in h.columns else h["close"].values[-1]
                    if prev_close > 0:
                        gap_pct = abs(today_open - prev_close) / prev_close
                        if gap_pct > self.max_gap_pct:
                            self._filter_skip_today = True
            except:
                pass

        # Overnight vol filter
        if self.use_overnight_vol and not self._filter_skip_today:
            for s, future in self.futures.items():
                key = self.symbol_keys[s]
                mapped = self.current_contracts.get(s)
                if mapped is None:
                    continue
                try:
                    h = self.history(mapped, 25, Resolution.DAILY)
                    if not h.empty and len(h) >= 21:
                        closes = h["close"].values
                        opens = h["open"].values if "open" in h.columns else closes
                        overnight_ranges = np.abs(opens[1:] - closes[:-1])
                        avg_20 = float(np.mean(overnight_ranges[-20:]))
                        current_overnight = float(overnight_ranges[-1]) if len(overnight_ranges) > 0 else 0
                        if avg_20 > 0 and current_overnight > self.overnight_vol_mult * avg_20:
                            self._filter_skip_today = True
                            break
                except:
                    pass

        # ML regime filter
        if self.use_ml_filter and self.ml_coefficients and not self._filter_skip_today:
            try:
                h = self.history(self._spy, 25, Resolution.DAILY)
                if not h.empty and len(h) >= 21:
                    closes = h["close"].values
                    rets = np.diff(closes) / closes[:-1]
                    realized_vol = float(np.std(rets[-20:], ddof=1) * np.sqrt(252))
                    spy_return_20d = float((closes[-1] / closes[-21] - 1.0)) if closes[-21] > 0 else 0.0

                    vix_val = self._current_vix if self._current_vix else 20.0
                    vix_change_5d = 0.0
                    if len(self._prev_vix_10d) >= 5:
                        vix_5d_ago = self._prev_vix_10d[-5]
                        if vix_5d_ago > 0:
                            vix_change_5d = (vix_val - vix_5d_ago) / vix_5d_ago

                    features = [realized_vol, vix_val, vix_change_5d, spy_return_20d]
                    coeffs = self.ml_coefficients
                    intercept = self.ml_intercept

                    # Logistic regression: sigmoid(intercept + sum(coeff_i * feature_i))
                    z = intercept
                    for feat, coeff in zip(features, [coeffs.get("realized_vol", 0),
                                                       coeffs.get("vix", 0),
                                                       coeffs.get("vix_change_5d", 0),
                                                       coeffs.get("spy_return_20d", 0)]):
                        z += feat * coeff
                    prob = 1.0 / (1.0 + np.exp(-z))
                    if prob < 0.5:
                        self._filter_skip_today = True
            except:
                pass

    def _record_daily(self):
        if self.is_warming_up:
            return

        eq = self.portfolio.total_portfolio_value
        year = self.time.year

        if year not in self._year_start_equity:
            self._year_start_equity[year] = eq
            self._daily_returns[year] = []
            self._vol_skip_count[year] = 0
            self._year_trades[year] = 0

        if self._prev_equity and self._prev_equity > 0:
            self._daily_returns[year].append((eq - self._prev_equity) / self._prev_equity)
        self._prev_equity = eq

        # Equity export
        if self.export_equity:
            today = self.time.strftime("%Y%m%d")
            if today != self._last_equity_date:
                self._equity_log.append(f"{today}:{eq:.0f}")
                self._last_equity_date = today

    def on_end_of_algorithm(self):
        # Yearly stats
        for year in sorted(self._year_start_equity.keys()):
            start_eq = self._year_start_equity[year]
            rets = self._daily_returns.get(year, [])
            n_trades = self._year_trades.get(year, 0)
            vol_skips = self._vol_skip_count.get(year, 0)
            if rets:
                arr = np.array(rets)
                mean_r = float(np.mean(arr))
                std_r = float(np.std(arr, ddof=1)) if len(arr) > 1 else 0.0
                sharpe = (mean_r / std_r * np.sqrt(252)) if std_r > 0 else 0.0
                cum = np.cumprod(1.0 + arr)
                end_eq = start_eq * cum[-1]
                annual_ret = (end_eq / start_eq - 1.0) * 100
                peak = np.maximum.accumulate(cum)
                max_dd = float(np.min(cum / peak - 1.0) * 100)
            else:
                sharpe = 0.0
                annual_ret = 0.0
                max_dd = 0.0
                end_eq = start_eq
            stat = f"{sharpe:.3f}|{annual_ret:.1f}|{max_dd:.1f}|{n_trades}|{vol_skips}|{end_eq:.0f}"
            self.set_runtime_statistic(f"y_{year}", stat)

        # Equity export
        if self.export_equity and self._equity_log:
            batch_size = 25
            n_batches = 0
            for i in range(0, len(self._equity_log), batch_size):
                batch = self._equity_log[i:i + batch_size]
                self.set_runtime_statistic(f"eq_{n_batches:03d}", "|".join(batch))
                n_batches += 1
            self.set_runtime_statistic("eq_count", str(n_batches))
            self.set_runtime_statistic("eq_total", str(len(self._equity_log)))
        elif self.export_equity:
            self.set_runtime_statistic("eq_count", "0")

    # ── State ───────────────────────────────────────────────────

    def _empty_state(self):
        return {
            "collecting": False, "range_set": False,
            "range_high": None, "range_low": None,
            "traded_today": False, "direction": None,
            "entry_price": None, "stop_price": None,
            "target_price": None, "mapped_symbol": None,
            "breakout_direction": None, "breakout_start_time": None,
        }

    def _reset_daily_state(self):
        for key in self.daily_state:
            self.daily_state[key] = self._empty_state()
        self._trend_cache = {}
        self._trend_cache_date = None
        self._vol_skip_today = False
        self._filter_skip_today = False

    def on_securities_changed(self, changes):
        for sec in changes.added_securities:
            if sec.symbol.security_type != SecurityType.BASE:
                sec.set_fee_model(InteractiveBrokersFeeModel())

    def _handle_rollovers(self):
        for s, future in self.futures.items():
            key = self.symbol_keys[s]
            mapped = future.mapped
            if mapped is None:
                continue
            prev = self._previous_contracts.get(s)
            self.current_contracts[s] = mapped
            if prev is not None and prev != mapped:
                if self.portfolio[prev].invested:
                    qty = self.portfolio[prev].quantity
                    self.liquidate(prev, tag=f"Roll out {key}")
                    self.market_order(mapped, qty, tag=f"Roll in {key}")
                    state = self.daily_state[key]
                    if state["mapped_symbol"] == prev:
                        state["mapped_symbol"] = mapped
            self._previous_contracts[s] = mapped

    def _get_trend_direction(self, symbol, key):
        today = self.time.date()
        if self._trend_cache_date != today:
            self._trend_cache = {}
            self._trend_cache_date = today
        if key in self._trend_cache:
            return self._trend_cache[key]
        try:
            h = self.history(symbol, self.sma_period + 5, Resolution.DAILY)
            if h.empty or len(h) < self.sma_period:
                direction = 0
            else:
                closes = h["close"].values
                sma_val = np.mean(closes[-self.sma_period:])
                direction = 1 if closes[-1] > sma_val else -1
        except:
            direction = 0
        self._trend_cache[key] = direction
        return direction

    # ── Main Trading Logic ──────────────────────────────────────

    def on_data(self, data):
        if self.is_warming_up:
            return

        # Update VIX
        if data.contains_key(self._vix):
            self._current_vix = data[self._vix].value
            self._prev_vix_10d.append(self._current_vix)
            if len(self._prev_vix_10d) > 15:
                self._prev_vix_10d = self._prev_vix_10d[-15:]

        self._handle_rollovers()

        spy_price = self.securities[self._spy].price
        if spy_price > 0:
            if self._spy_start_price is None:
                self._spy_start_price = spy_price
            self.plot("Strategy Equity", "SPY Buy & Hold",
                      self._initial_capital * (spy_price / self._spy_start_price))

        now = self.time
        if now.weekday() == 0:
            return

        # Dual vol filter
        if self.use_dual_vol_filter and self._vol_skip_today:
            return

        # Novel regime filters
        if self._filter_skip_today:
            return

        # Adaptive range: compute dynamic range filter bounds
        adaptive_min_range = self.min_range_pct
        adaptive_max_range = self.max_range_pct
        if self.use_adaptive_range:
            try:
                h = self.history(self._spy, self.adaptive_atr_period + 5, Resolution.DAILY)
                if not h.empty and len(h) >= self.adaptive_atr_period:
                    highs = h["high"].values if "high" in h.columns else h["close"].values
                    lows = h["low"].values if "low" in h.columns else h["close"].values
                    atrs = highs - lows
                    atr_pctile = float(np.percentile(atrs[-self.adaptive_atr_period:], 50))
                    mid_price = float(h["close"].values[-1])
                    if mid_price > 0:
                        adaptive_min_range = max(0.0005, atr_pctile / mid_price * 0.3)
                        adaptive_max_range = min(0.025, atr_pctile / mid_price * 3.0)
            except:
                pass

        for s, future in self.futures.items():
            key = self.symbol_keys[s]
            cfg = self.instrument_configs[key]
            state = self.daily_state[key]
            mapped = self.current_contracts.get(s)
            if mapped is None:
                continue

            price = self.securities[mapped].price
            if price <= 0:
                continue

            range_start = now.replace(hour=cfg["range_start_hour"], minute=cfg["range_start_min"], second=0)
            range_end = now.replace(hour=cfg["range_end_hour"], minute=cfg["range_end_min"], second=0)

            if range_start <= now < range_end and not state["range_set"]:
                state["collecting"] = True
                if state["range_high"] is None or price > state["range_high"]:
                    state["range_high"] = price
                if state["range_low"] is None or price < state["range_low"]:
                    state["range_low"] = price
                continue

            if state["collecting"] and now >= range_end and not state["range_set"]:
                state["collecting"] = False
                state["range_set"] = True
                rh, rl = state["range_high"], state["range_low"]
                if rh and rl and rh > rl:
                    range_pct = (rh - rl) / ((rh + rl) / 2)
                    min_r = adaptive_min_range if self.use_adaptive_range else self.min_range_pct
                    max_r = adaptive_max_range if self.use_adaptive_range else self.max_range_pct
                    if range_pct < min_r or range_pct > max_r:
                        state["traded_today"] = True
                else:
                    state["traded_today"] = True

            if not state["range_set"] or state["traded_today"]:
                continue

            flatten_time = now.replace(hour=cfg["flatten_hour"], minute=cfg["flatten_min"], second=0)
            if now >= flatten_time - timedelta(minutes=30):
                if state["direction"]:
                    self._check_exit(key, price, mapped)
                continue

            rh, rl = state["range_high"], state["range_low"]
            range_width = rh - rl

            if state["direction"] is None:
                if state["breakout_direction"]:
                    elapsed = (now - state["breakout_start_time"]).total_seconds() / 60
                    still_valid = (
                        (state["breakout_direction"] == "long" and price > rh) or
                        (state["breakout_direction"] == "short" and price < rl)
                    )
                    if not still_valid:
                        state["breakout_direction"] = None
                        state["breakout_start_time"] = None
                    elif elapsed >= self.confirmation_minutes:
                        qty = self._calc_position_size(mapped, range_width, cfg)
                        if qty > 0:
                            if state["breakout_direction"] == "long":
                                self.market_order(mapped, qty, tag=f"{key} LONG")
                                state["direction"] = "long"
                                state["entry_price"] = price
                                state["stop_price"] = rl
                                state["target_price"] = price + self.reward_risk_ratio * range_width
                            else:
                                self.market_order(mapped, -qty, tag=f"{key} SHORT")
                                state["direction"] = "short"
                                state["entry_price"] = price
                                state["stop_price"] = rh
                                state["target_price"] = price - self.reward_risk_ratio * range_width
                            state["traded_today"] = True
                            state["mapped_symbol"] = mapped
                        state["breakout_direction"] = None
                        state["breakout_start_time"] = None
                else:
                    trend = self._get_trend_direction(s, key)
                    if price > rh and trend >= 0:
                        state["breakout_direction"] = "long"
                        state["breakout_start_time"] = now
                    elif price < rl and trend <= 0:
                        state["breakout_direction"] = "short"
                        state["breakout_start_time"] = now
            elif state["direction"]:
                self._check_exit(key, price, mapped)

    def _check_exit(self, key, price, mapped):
        state = self.daily_state[key]
        if state["direction"] == "long":
            if price <= state["stop_price"] or price >= state["target_price"]:
                self.liquidate(mapped, tag=f"{key} EXIT")
                state["direction"] = None
        elif state["direction"] == "short":
            if price >= state["stop_price"] or price <= state["target_price"]:
                self.liquidate(mapped, tag=f"{key} EXIT")
                state["direction"] = None

    def _calc_position_size(self, mapped, range_width, cfg):
        sec = self.securities[mapped]
        mult = sec.symbol_properties.contract_multiplier
        if not mult or mult <= 0:
            mult = 1
        risk_per_contract = range_width * mult
        if risk_per_contract <= 0:
            return 0
        portfolio_value = self.portfolio.total_portfolio_value
        dollar_risk = portfolio_value * cfg["risk_per_trade"]
        target_qty = int(dollar_risk / risk_per_contract)
        return max(1, min(target_qty, self.max_contracts))

    def _flatten_all(self):
        for s in self.futures:
            key = self.symbol_keys[s]
            mapped = self.current_contracts.get(s)
            if mapped and self.portfolio[mapped].invested:
                self.liquidate(mapped, tag=f"{key} EOD flatten")
            self.daily_state[key]["direction"] = None

    def on_order_event(self, order_event):
        if order_event.status == OrderStatus.FILLED:
            year = self.time.year
            if year in self._year_trades:
                self._year_trades[year] += 1
            order = self.transactions.get_order_by_id(order_event.order_id)
            self.log(f"[ORDER] FILLED | {order_event.symbol} | "
                     f"qty={order_event.fill_quantity} @ {order_event.fill_price:.2f} | "
                     f"tag={order.tag if order else 'N/A'}")
